name: Monthly Notion Update

on:
  schedule:
    - cron: '0 0 16 * *'  # 每月16日 00:00 UTC 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update_notion:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas
    - name: Run monthly Notion update
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}
      run: python monthly2notion.py
